### ISSUE TITLE
Unable to set Colour_Key

### ISSUE THREAD

**Issue by rveenker** [Lucretia/sdlada#10]
This issue is a follow-op on issue #9.

Unfortunately that issue was only partially solved, hence this new issue. Sorry for the confusion.

I found that running a program that calls Set_Colour_Key (SDL_SetColorKey) raises an Exception_Access_Violation exception.
(on my Win10 machine this is a segmentation fault in SDL2.dll: 
0x6c7e490d in SDL_LogCritical() from SDL2dll
Version SDL 2.0.7 32bits - SDL2.dll 23-10-2017 996.352 bytes)

Also I added the extra ´Flag' parameter and created a simple pixel value, but to no avail.

BTW, there is an SDL2 example in C++ that does work: http://lazyfoo.net/tutorials/SDL/10_color_keying/index.php

By comparing the resulting surfaces just before SDL_SetColorKey is called, I was trying to find out what was wrong, but I haven't found it yet...

**Comment by rveenker** [comment]
I think I found the problem.
Apparently the SDL_SetColorKey should not be passed the Internal_Surface_Pointer, but the Internal_Surface itself.
A bit strange but it appears to work :-)

**Comment by Lucretia** [comment]
Had to think about this for a while. The surface should be in not in out, but I've added a comment there for later reference.

**Comment by rveenker** [comment]
This had crossed my mind also and I agree that in is the best solution.
Note however that this also applies to other procedures and functions in sdl-video-surfaces!

**Comment by Lucretia** [comment]
Have fixed the other functions with ```in out Internal_Surface_Pointer``` to be just ```in Internal_Surface_Pointer``` parameters, so they should work now.
