### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by TanMax2008** [Lucretia/sdlada#100]
#include <SFML/Graphics.hpp>
int main() {
    sf::RenderWindow window(sf::VideoMode(800, 600), "Simple 2D Gam

    // Tạo hình chữ nhật đại diện cho nhân vật
    sf::RectangleShape player(sf::Vector2f(50.0f, 50.0f));
    player.setFillColor(sf::Color::Green);
    
    // Đặt vị trí ban đầu của nhân vật
    player.setPosition(375.0f, 275.0f);

    while (window.isOpen()) {
        sf::Event event;
        while (window.pollEvent(event)) {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        // Xử lý đầu vào - di chuyển nhân vật
        if (sf::Keyboard::isKeyPressed(sf::Keyboard::Left)) {
            player.move(-5.0f, 0.0f);
        }
        if (sf::Keyboard::isKeyPressed(sf::Keyboard::Right)) {
            player.move(5.0f, 0.0f);
        }
        if (sf::Keyboard::isKeyPressed(sf::Keyboard::Up)) {
            player.move(0.0f, -5.0f);
        }
        if (sf::Keyboard::isKeyPressed(sf::Keyboard::Down)) {
            player.move(0.0f, 5.0f);
        }

        window.clear();
        // Vẽ nhân vật lên cửa sổ
        window.draw(player);
        window.display();
    }

    return 0;
}

**Comment by Lucretia** [comment]
You're in the wrong place, this is SDLAda not ASFML.
