### ISSUE TITLE
sdl v208?

### ISSUE THREAD

**Issue by fastrgv** [Lucretia/sdlada#29]
Luke,  
I see sdlada currently supports sdl207.  Do you have yet a sense of how different 208 is?  
I have a c++ code that compiles using 207 headers and 208 libraries that seems to work Ok, given the limited interfaces my code actually uses.
I am planning to try using sdlada soon, but it would be even sooner if I knew you had support for 208 coming soon.  Are you planning an update any time soon?
(feel free to close this issue since it's just a question...could not find your email anywhere...)
thx, 
Rod <fastrgv@gmail.com>

**Comment by Lucretia** [comment]
There really shouldn't be too much that's different between the versions, SDLAda should work fine with it.  SDL is usually upwards compatible anyway.

**Comment by fastrgv** [comment]
Good, that's what I was hoping to hear.
