### ISSUE TITLE
Errors at make

### ISSUE THREAD

**Issue by dead-crow** [Lucretia/sdlada#3]
Hi , i  just want to use the library .
I unzip the archive and open a terminal into it .
When i  apply the README file , i got the following errors =
How solve the problem ?

dead-code@Machine:~/Bureau/sdlada-master$ make SDL_PLATFORM=linux SDL_BUILD=static SDL_MODE=release
gprbuild -p -gnat2012 -XSDL_BUILD=static -XSDL_MODE=release -XSDL_PLATFORM=linux \
		-Psdlada.gpr -cargs `sdl2-config --cflags`
sdl_version.gpr:1:09: warning: there are no Ada sources in this project
gcc-4.6 -c -ffunction-sections -fdata-sections -gnat2012 -gnata -gnato -gnatE -gnaty -gnaty-s -gnatyO -gnatyM120 -gnatyO -O2 -I/usr/include/SDL2 -D_REENTRANT -gnat2012 sdl-events-keyboards.adb
sdl-events-keyboards.adb:30:09: aspect identifier expected
sdl-events-keyboards.adb:39:09: aspect identifier expected
sdl-events-keyboards.adb:48:09: aspect identifier expected
sdl-events-keyboards.adb:57:09: aspect identifier expected
sdl-events-keyboards.adb:67:09: aspect identifier expected
sdl-events-keyboards.adb:77:09: aspect identifier expected
gprbuild: *** compilation phase failed
make: *** [sdl_build.gpr] Erreur 4
dead-code@Machine:~/Bureau/sdlada-master$

I use Ubuntu 14.04 LTS in 32 bits.

**Comment by Lucretia** [comment]
You will need a newer compiler, gcc-4.6 isn't good enough, at least 4.9.

**Comment by dead-crow** [comment]
gcc 4.8 is well present as you can see . But he is not used in the make , idon't know why .
Beside, I still got errors .

dead-code@Machine:~/Bureau/sdlada-master$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

dead-code@Machine:~/Bureau/sdlada-master$ 

Maybe there is another place where people can discuss about issues , like a forum ? :)

**Comment by Lucretia** [comment]
Freenode #Ada channel

**Comment by dead-crow** [comment]
Thanks
