### ISSUE TITLE
Range check failed in SDL.Video.Windows

### ISSUE THREAD

**Issue by onox** [Lucretia/sdlada#31]
Range check failed in `sdl-video-windows.adb:158` when `Total` = 0:

https://github.com/Lucretia/sdlada/blob/7093d75264088c79104e9e02f45053e919cbf523/src/sdl-video-windows.adb#L158

**Comment by Lucretia** [comment]
Fixed as of commit 0b4394ecaf8dc359e085183a8952721418dbfdf4
