### ISSUE TITLE
Invalid data value when reading mouse scroll wheel

### ISSUE THREAD

**Issue by onox** [Lucretia/sdlada#32]
Trying to read `Event.Mouse_Wheel.X` (or `Y`) results in a Contstraint_Error: `invalid data value -15 not in -1..1`.

https://github.com/Lucretia/sdlada/blob/7093d75264088c79104e9e02f45053e919cbf523/src/sdl-events-mice.ads#L121-L123

Reverting the range of `Wheel_Values` back to `-2 ** 31 .. 2 ** 31 - 1` avoids the exception.

**Comment by Lucretia** [comment]
I have no idea how your mouse is generating those values, it should be -1 .. 1. See [here](https://www.freepascal-meets-sdl.net/chapter-8-pt-2-mouse-handling):

> New fields here are the x and y field which do not correspond to the mouse cursor position this time. Instead of that they refer to the direction of the mouse wheel being scrolled. If you scroll the mouse wheel upwards or forward it will return 1, and if you scroll it backwards it will return -1.

**Comment by Lucretia** [comment]
Fixed as of commit c9866b206cd746a7eb2ac012fa8686f4d4c2226f.

Still think this should be scaled in some way.

**Comment by onox** [comment]
I've been doing some more debugging on another machine which has still an X server via Xwayland:

1. GLFW via X11 is OK (scrolling down -- topside moves towards you -- generates -1, horizontal scroll to the right generates -1 as well)
2. SDL via X11 is OK (-1 when scrolling down or to the right)
3. GLFW via Wayland has the X and Y axis of the mouse wheel inverted (scrolling down/right generates positives values)
4. SDL via Wayland has axis correct (negative when scrolling down/right), but the absolute value is 10 instead of 1

Haven't figured out yet whether this is a bug in (possibly) libinput or whether Wayland allows these large values (I guess the latter).

I'll notify the GLFW developers about the inverted axis.
