### ISSUE TITLE
Constraint_Error when reading Event.Window.Event_ID

### ISSUE THREAD

**Issue by onox** [Lucretia/sdlada#40]
Reading `Event.Window.Event_ID` generates a Constraint_Error with the message "invalid data value 15 not in 0..14.

The following two values are missing and need to be appended after `Close`:

1. `Take_Focus`
2. `Hit_Test`

See `SDL_WindowEventID` in `SDL_video.h` on lines 168 and 169.

SDL driver: X11

**Comment by Lucretia** [comment]
This is because I didn't update since 2.0.4. Fixed as of commit [bdb2101](https://github.com/Lucretia/sdlada/commit/bdb2101d26346d78e21fe6504538331cdfb66599)
