### ISSUE TITLE
Incorrect Key_Codes constants in sdl-events-keyboards.ads

### ISSUE THREAD

**Issue by docandrew** [Lucretia/sdlada#44]
Hello, it seems that the wrong constants are being generated for the sdl-events-keyboards.ads file.

Reference: https://wiki.libsdl.org/SDLKeycodeLookup, which shows 0x40000000 as the or-ed mask.

I believe line 368 in tools/gen_keyboard.adb should change from:
```
Internal_To_Key_Code_Mask : constant Key_Codes := 16#2000_0000#
```
to:
```
Internal_To_Key_Code_Mask : constant Key_Codes := 16#4000_0000#
```

I just edited the generated file to give me the correct key codes, which was a good workaround without me having to rebuild SDLAda. Thank you!

**Comment by Lucretia** [comment]
Fixed
