### ISSUE TITLE
Set_Context_Profile sets wrong profile or crashes

### ISSUE THREAD

**Issue by sf17k** [Lucretia/sdlada#5]
SDL.Video.GL.Set_Context_Profile accepts either Core, Compatibility, or ES, but the resulting context doesn't match. Traced the problem to sdl-video-gl.adb:470:

```
Result : C.int := SDL_GL_Set_Attribute (Attribute_Context_Profile, C.int (Profile_Values (Profile)));
```

Profile_Values is the array (1, 2, 4) and is being indexed incorrectly by Profile, an enum that itself has value 1, 2, or 4. I think Profile_Values is safe to remove, it's redundant and doesn't seem to be used anywhere else.

**Comment by Lucretia** [comment]
Fixed.
