### ISSUE TITLE
Set_Colour_Key not working

### ISSUE THREAD

**Issue by jquorning** [Lucretia/sdlada#57]
Set_Color_Key does not work on macOS with SDL2 version 2.0.10.
It works with Homebrew SDL2 version 2.0.12.
Suggest to introduce optional flag SDL_FRAMEWORK=False/True for frameworks.
I will make patch when approved.

**Comment by Lucretia** [comment]
Does colour keying work on macos with the C SDL lib?

Before you submit a patch, what would this flag do?

**Comment by jquorning** [comment]
C SDL lib?
Colour keying works with the SDL2 lib from Homebrew (not a framework).
The SDL_FRAMEWORK flag should replace __APPLE__ in version_ttf.c etc so that we have the choice of using the Homebrew (libSDL2) and native macOS (framework). Otherwise SDL_PLATFORM could include "macosx_homebrew" "macosx_framework" or so.

**Comment by Lucretia** [comment]
I still don't understand this. Are you saying that colour keying works with the "brew" version of SDL but not the framework? If that's the case, I'm not going to accept a patch for a bug in another package. The bug report needs to go to the SDL lot who build that framework.

**Comment by jquorning** [comment]
This problem may be due to compromised platform. I will create new Issue about brew.
