### ISSUE TITLE
Suggestion: Remove dependence on C

### ISSUE THREAD

**Issue by jquorning** [Lucretia/sdlada#77]
When I have tried to get SDLAda working on Mac most of the trouble is about getting the version info working.
All ado about som library versions that I do not check or care much about anyway.
Therefore I suggest removing dependance on C sources in the main project.
This will imo make it much easier for newcomers to use SDLAda.
Perhaps version info (in needed) could be put into a separate gpr file and postpone version checking until link time.

**Comment by Lucretia** [comment]
No. Just because you do not care, does not mean there is not real functionality in there. GPRBuild just builds the C sources, it's not a problem. They are there for things that cannot be done in Ada.

I've literally just added a warning to version:

```
--  **IMPORTANT** DO NOT REMOVE THESE FUNCTIONS, they are very important. They allow the running application to see
--                what version of the libraries are installed on the system. This allows the running application
--                to modify it's behaviour if certain functionality from a certain version is missing.
--                i.e. Steam controls it's libs and whilst they are usually up to date, there is no guarantee that
--                the version you built against has the same functionality as that installed on the user's machine.
```
