### ISSUE TITLE
Unable to get or set Colour_Key

### ISSUE THREAD

**Issue by rveenker** [Lucretia/sdlada#9]
The routines SDL.Video.Surfaces.Colour_Key (calls SDL_GetColorKey)
and SDL.Video.Surfaces.Set_Colour_Key (calls SDL_SetColorKey) both crash with an exception Surface_Error.
I need the Set_Colour_Key  in order to make my image (bmp) transparent.

To test these functions, I added some calls to the load_image.adb example (just after Window_Surface := W.Get_Surface) :
declare 
    Color_Key        : SDL.Video.Palettes.Colour;
begin
   Color_Key := SDL.Video.Surfaces.Colour_Key (Window_Surface);
end;

I noticed that the Set_Colour_Key procedure was missing a parameter for flags, but fixing this did not help.

Any help is greatly appreciated :-)

**Comment by Lucretia** [comment]
What message is printed with the exception? All the exceptions should call SDL_GetError in the raise statement.

**Comment by rveenker** [comment]
I just added an exception handler with an occurrence variable 'e'.
Printing 'e' in the debugger gives me:
 
(gdb) print e
$1 = (id => 0x460a18 <sdl.video.surfaces.surface_error>, machine_occurrence => (system.address) 0x0, msg_length => 0, msg => "["e6"] .......

So there is no extra info from SDL.

**Comment by Lucretia** [comment]
Also, do you have a quick test program you can upload and i'll try it here? Ta.

**Comment by Lucretia** [comment]
What OS are you on?

**Comment by Lucretia** [comment]
If you are on Windows, can you do what it says in #4 and come back to me? I've only just set up windows 10 on a VM, I'm yet to get a compiler and SDLAda compiling on it.

**Comment by rveenker** [comment]
I'm on Win7

**Comment by Lucretia** [comment]
Ok, might be issue #4 then. If that works for you, I'll modify the calls and push.

**Comment by rveenker** [comment]
I just made the change to SDL-log.adb as described in #4 but the message is still empty.

**Comment by Lucretia** [comment]
Ok, can you upload a simple test that fails and i'll try it here?

**Comment by rveenker** [comment]
I'll use the load_surface example with my modification.
My company machine has no internet connection, so I'll take it home and upload it to my website later.

**Comment by Lucretia** [comment]
It's ok, I've just tried it here.

**Comment by Lucretia** [comment]
ok, according to [SDL_GetColorKey](https://wiki.libsdl.org/SDL_GetColorKey?highlight=%28%5CbCategoryAPI%5Cb%29%7C%28SDLFunctionTemplate%29) it should return -1 if there is no colour key, which it does, but libSDL doesn't set an error message.

**Comment by Lucretia** [comment]
In fact, it's actually returning a string containing null, "\0"!

**Comment by Lucretia** [comment]
Ok, pull the latest. It's an error with SDL_GetColorKey

**Comment by rveenker** [comment]
Ok, I understand that this was indeed the problem for getting the ColorKey.
However the problem with setting the ColorKey still exists.

Running a program that calls Set_Colour_Key (SDL_SetColorKey) raises an Exception_Access_Violation exception.
I have added the extra ´Flag' parameter and created a simple pixel value, but to no avail.
Sorry for the confusion.
